dev:
  name: "development"
  url : "http://localhost:9200"
  index: "twitter"
  search: "bye"
  date_field: "@timestamp"
  fields: ["user","message"]
  to: "joel.holder@amd.com"
  from: "esbadmins@amd.com"
  smtp_server: "txsmtp.amd.com"
  send: true
qa:
  name: "QA"
  url : "http://esbanl01-qa.amd.com:9200?ignore_unavailable=true"
  # index: "logstash-*"
  # index: "logstash-2015.09.*"
  # index: "logstash-2015.09.14,logstash-2015.09.15,foobar123"
  search: 'message:"*exception*"'
  date_field: "@timestamp"
  fields: ["host","path","logdate","level","messagetext","category","contextId","thread","routeId","breadcrumbId"]  
  to: "joel.holder@amd.com"
  from: "esbadmins@amd.com"
  smtp_server: "txsmtp.amd.com"
  send: true
prod:
  name: "production"
  url : "http://esbanl01.amd.com:9200?ignore_unavailable=true"  
  search: 'message:"*exception*"'
  fields: ["host","path","logdate","level","messagetext","category","contextId","thread","routeId","breadcrumbId"]
  date_field: "@timestamp"
  to: "joel.holder@amd.com"
  from: "esbadmins@amd.com"
  smtp_server: "txsmtp.amd.com"
  send: true